### ISSUE TITLE
Mojolicious error

### ISSUE THREAD

**Issue by CRHASH** [ath88/battlefield-2-unlocks-hack#1]
Hello

I can't get this to work. I have ubuntu desktop 12.04 and i have installed the battlefield 2 server. But i get stuck on this step: After you finished installing the dedicated server all you need to do is go to the git directory in terminal an execute unlockserver "./unlockserver".

When i try to do that this happens:

Can't locate Mojolicious/Lite.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at unlockserver.pl line 6.
BEGIN failed--compilation aborted at unlockserver.pl line 6.

I have tried to google this problem, and it seems to have to do with Mojolicious. But with my nonexisting  linux skills, i can't solve it.
//CRHASH

**Comment by ath88** [comment]
Hi there! Thanks for opening the issue!

You will need to actually install Mojolicious. Thanks to Perl-y goodness, you can do so by issuing the command;

sudo cpan Mojolicious

Note that this will install Mojolicious to your 'system Perl'. This is fine if you are not Linux-savvy, but some people might install another Perl for running user software.

I hope this does still work though, since I've heard rumors that the entire BF2 server structure has been shut down, and this solution relies on intercepting some of the communication between the servers.

I hope this satisfies your question.

**Comment by CRHASH** [comment]
Hello again !

It seems like it is like you said that it dosent work because of the gamespy shutdown.

Anyway thanks for the quick answer. I will have to find another solution.
//CRHASH

**Comment by ath88** [comment]
That is probably right. I will correct the README to reflect this, so no other people will waste time trying to make this work. It worked once upon a time, however. :)

Take a look at the BF2 Revive project over at [battlelog.co](http://battlelog.co). If you find it to work with a Linux server, I would love to hear from you. :)
